In [1]:
import pandas as pd

In [4]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f"{prefix}/yellow_tripdata_2021-01.csv.gz"
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [5]:
df = pd.read_csv(url)

/tmp/ipykernel_11392/4176769558.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [7]:
len(df)

1369765

In [8]:
df['VendorID']

0          1.0
1          1.0
2          1.0
3          1.0
4          2.0
          ...
1369760    NaN
1369761    NaN
1369762    NaN
1369763    NaN
1369764    NaN
Name: VendorID, Length: 1369765, dtype: float64

In [13]:
#Il comando sotto specifica il tipo per ogni colonna della tabella

In [10]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [20]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [23]:
!uv add sqlalchemy psycopg2-binary

Resolved 119 packages in 894ms
Prepared 3 packages in 118ms
░░░░░░░░░░░░░░░░░░░░ [0/3] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 36ms
 + greenlet==3.3.0
 + psycopg2-binary==2.9.11
 + sqlalchemy==2.0.45

In [24]:
#Create Database Connection

In [25]:
from sqlalchemy import create_engine

In [27]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [29]:
#Get DDL Schema

In [31]:
df.to_sql(name='yellow_taxi_data', con=engine)

765

In [32]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [34]:
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [36]:
len(df)

1369765

In [48]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True, 
    chunksize=100000,
)

In [38]:
df_iter

In [41]:
df = next(df_iter)

In [46]:
len(df)

69765

In [50]:
!uv add tdqm

Resolved 121 packages in 462ms
Prepared 2 packages in 1.15s
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 5ms
 + tdqm==0.0.1
 + tqdm==4.67.1

In [51]:
from tqdm.auto import tqdm

In [52]:
for df_chunk in tqdm(df_iter): 
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]

In [53]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1300000,<NA>,2021-01-05 10:38:40,2021-01-05 10:46:20,<NA>,1.30,<NA>,<NA>,170,161,<NA>,7.00,0.0,0.5,1.03,0.00,0.3,11.33,2.5
1300001,<NA>,2021-01-05 10:17:14,2021-01-05 10:41:21,<NA>,7.90,<NA>,<NA>,216,198,<NA>,31.49,0.0,0.5,2.75,0.00,0.3,35.04,0.0
1300002,<NA>,2021-01-05 10:39:00,2021-01-05 10:46:00,<NA>,0.98,<NA>,<NA>,62,62,<NA>,16.23,0.0,0.5,2.75,0.00,0.3,19.78,0.0
1300003,<NA>,2021-01-05 10:05:00,2021-01-05 10:19:00,<NA>,1.59,<NA>,<NA>,85,71,<NA>,13.45,0.0,0.5,2.75,0.00,0.3,17.00,0.0
1300004,<NA>,2021-01-05 10:18:08,2021-01-05 10:41:40,<NA>,9.87,<NA>,<NA>,236,208,<NA>,30.23,0.0,0.5,2.75,6.12,0.3,39.90,0.0
1300005,<NA>,2021-01-05 10:06:19,2021-01-05 10:26:11,<NA>,10.28,<NA>,<NA>,185,235,<NA>,22.93,0.0,0.5,2.75,0.00,0.3,26.48,0.0
1300006,<NA>,2021-01-05 10:10:02,2021-01-05 10:28:14,<NA>,7.14,<NA>,<NA>,55,155,<NA>,24.42,0.0,0.5,2.75,0.00,0.3,27.97,0.0
1300007,<NA>,2021-01-05 10:49:03,2021-01-05 11:02:57,<NA>,1.50,<NA>,<NA>,236,161,<NA>,12.50,0.0,0.5,3.16,0.00,0.3,18.96,2.5
1300008,<NA>,2021-01-05 10:01:50,2021-01-05 11:01:03,<NA>,11.81,<NA>,<NA>,265,92,<NA>,31.68,0.0,0.5,0.00,0.00,0.3,32.48,0.0
1300009,<NA>,2021-01-05 10:43:18,2021-01-05 11:06:16,<NA>,9.78,<NA>,<NA>,83,244,<NA>,28.46,0.0,0.5,2.75,6.12,0.3,38.13,0.0

In [54]:
len(df)

69765